drop table comment if exists;
drop table image if exists;
drop table meal if exists;
drop table meal_product if exists;
drop table recipe_product if exists;
drop table product if exists;
drop table recipe if exists;
drop table user if exists;
drop table weight_log if exists;